defaults:
    - logger: wandb
    - credentials: default
    - platform: slurm
    - platform@platform_local: slurm
    - _self_

use_wandb: true
wandb_project_name: NeMo

seed_number: 0
training:
    scale_iterations_per_epoch: 1.0

inference:
    visualize_num_samples: 0
