defaults:
  - logger: wandb
  - methods@method.nemo: nemo_rec
  - methods/dataset@method.nemo: co3d
  - datasets@train_datasets.labeled: shapenet_ico_sub1 # _bic # co3d_no_zsp_50s_aligned
  - datasets@val_datasets.main: shapenet_ico_sub1 # _bic # co3d_no_zsp_50s_aligned
  - datasets@test_datasets.co3d: shapenet_ico_sub1
  - datasets@texture_dataset: dtd
  - ablations/co3d_refs@: r0
  - platform@platform_local: slurm
  - platform: slurm
  - _self_

mesh_type: 'alpha500' # note: this is anyway ignored as we are using dmtet

mesh_type_aligned: 'alpha500'
aligned_name: 'aligned_N_${mesh_type_aligned}_dinov2s/${co3d_refs.ref_name}'
# mesh_type_used: 'alphauniform250'

modalities:
    - 'size'
    - 'category'
    - 'category_id'
    - 'cam_intr4x4'
    - 'cam_tform4x4_obj'
    - 'category'
    - 'rgb'
    - 'rgb_mask'
    - 'mask'
    - 'mask_dt'
    - 'mask_inv_dt'
    - 'sequence_name_unique'
    - 'sequence'
    - 'mesh'
    - 'pcl'

#table_metrics:
#  test/co3d_no_zsp_5s_labeled_ref/geo,test/co3dv1_zsp_10s/geo,test/co3d_no_zsp_5s_labeled_ref/pose/acc_pi6,test/co3dv1_zsp_10s/pose/acc_pi6
#  - test/co3d_no_zsp_5s_labeled_ref/pose/acc_pi6
#  - test/co3dv1_zsp_10s/geo
#  - test/co3dv1_zsp_10s/pose/acc_pi6

test_subset_fraction: 1.
val_subset_fraction: 0.1

checkpoint_opt:
test: True
train: True
checkpoint: # ${checkpoint_opt} #  ${platform.path_exps}/__LAST_RUN__/nemo.ckpt # 03-20_15-51-46_CO3D_NeMo_bicycle_slurm # note: not rfpath automatic now /nemo.ckpt
# checkpoint: ${platform.path_exps}/08-28_15-22-55_CO3D_NeMo_dense_app0_meshes_x_gaussians_cat_def_bic50_slurm/nemo.ckpt

#train: False
#checkpoint: ${platform.path_exps}/__LAST_RUN__/nemo.ckpt

skip_cross_pascal3d: False
skip_cross_pascal3d_occ: ${skip_cross_pascal3d} # False

skip_spair71k: False
skip_cross_objectnet3d: True

skip_co3d_zsp_val: True
skip_co3d_zsp_test: False
skip_co3d_no_zsp_test: False

train_sequences_count_max_per_category: 50

categories:
  - chair
#  - motorcycle
#  - truck
#  - train
#  - teddybear
#  - car
#  - bus
#  - motorcycle
#  - keyboard
#  - handbag
#  - remote
#  - airplane
#  - toilet
#  - hairdryer
#  - mouse
#  - toaster
#  - hydrant
#  - chair
#  - laptop
#  - book
#  - backpack
#  - cellphone # from cellphone on, no zsp categories
#  - microwave
#  - bench
#  - bottle
#  - couch
#  - cup
#  - suitcase
#  - tv

metrics:
  - metricA
  - metricB


method:
  nemo:
    name: nemo
    class_name: NeMo_Rec

    model:
      head:
        normalize: True
    train:

      early_stopping_score: loss
      # Basically you can ignore this, I used it to implement topography loss, I saw it in one of the code bases
      loss:
        geo:
          rec:
            type: cd_pcl # cd_mesh, cd_pcl, pf_mesh, pf_pcl
            weight: 0.1
          mask:
            weight: 0.0
          mask_mse:
            weight: 1.0
          mask_dt:
            weight: 100.0
          mask_inv_dt:
            weight: 0.0
          smooth:
            weight: 0.0
          sdf_reg:
            weight: 0.01
          deform_smooth_reg:
            weight: 0.01
          deform_reg:
            weight: 0.1
          deform_latent_reg:
            type: unit
            weight: 0.0
          topology_loss:
            weight: 1.0  
        appear:
          type: cross_entropy_coarse
          dropout: 0.0
          dense_loss: True
          dense_detach_geo: False
          weight: 0.1
          use_mask_rgb: True
          use_mask_object: False
        pose:
          weight: 1.0
      split: sequences_separated
      val_fraction: 0.1
      optimizer:
        kwargs:
        # Reducing the learing rate according to the instruction from the sessions, 
        # When I used lower value, the was no training at all, 1e-4 is the optimal, it's low enough
          lr: 1e-4 #1e-4 # 0.0001
      val: True
      T: 0.07
      early_stopping: True
      epochs: 500 # 300 500 - increased for better convergence
      epochs_to_next_test: 25
      dataloader:
        num_workers: 8
        batch_size: 10
    test:
      dataloader:
        num_workers: 8
        batch_size: 11
      transform:
        class_name: SequentialTransform
        transforms:
        - class_name: CenterZoom3D
          W: 512
          H: 512
          scale:
          scale_with_mask: 1.
          center_rel_shift_xy:
            - -0.
            - -0.
        - class_name: RGB_UInt8ToFloat

    categories: ${categories}
    path_meshes_tform: ${train_datasets.labeled.path_preprocess}/tform_obj/label3d_cuboid/meta_mask/meta
    path_meshes: ${train_datasets.labeled.path_preprocess}/mesh/${mesh_type}/meta_mask/meta
    fpaths_meshes:
      bicycle: None # ${..path_meshes}/bicycle/${co3d_refs.bicycle}/mesh.ply
      truck: None # ${..path_meshes}/toytruck/${co3d_refs.toytruck}/mesh.ply
      train: None # ${..path_meshes}/toytrain/${co3d_refs.toytrain}/mesh.ply
      teddybear: None # ${..path_meshes}/teddybear/${co3d_refs.teddybear}/mesh.ply
      car: None # ${..path_meshes}/car/${co3d_refs.car}/mesh.ply
      bus: None # ${..path_meshes}/toybus/${co3d_refs.toybus}/mesh.ply
      motorcycle: None # ${..path_meshes}/motorcycle/${co3d_refs.motorcycle}/mesh.ply
      keyboard: None # ${..path_meshes}/keyboard/${co3d_refs.keyboard}/mesh.ply
      handbag: None # ${..path_meshes}/handbag/${co3d_refs.handbag}/mesh.ply
      remote: None # ${..path_meshes}/remote/${co3d_refs.remote}/mesh.ply
      airplane: None # ${..path_meshes}/toyplane/${co3d_refs.toyplane}/mesh.ply
      toilet: None # ${..path_meshes}/toilet/${co3d_refs.toilet}/mesh.ply
      hairdryer: None # ${..path_meshes}/hairdryer/${co3d_refs.hairdryer}/mesh.ply
      mouse: None # ${..path_meshes}/mouse/${co3d_refs.mouse}/mesh.ply
      toaster: None # ${..path_meshes}/toaster/${co3d_refs.toaster}/mesh.ply
      hydrant: None # ${..path_meshes}/hydrant/${co3d_refs.hydrant}/mesh.ply
      chair: None # ${..path_meshes}/chair/${co3d_refs.chair}/mesh.ply
      laptop: None # ${..path_meshes}/laptop/${co3d_refs.laptop}/mesh.ply
      book: None # ${..path_meshes}/book/${co3d_refs.book}/mesh.ply
      backpack: None # ${..path_meshes}/backpack/${co3d_refs.backpack}/mesh.ply
      cellphone: None # ${..path_meshes}/cellphone/${co3d_refs.cellphone}/mesh.ply
      microwave: None # ${..path_meshes}/microwave/${co3d_refs.microwave}/mesh.ply
      bench: None # ${..path_meshes}/bench/${co3d_refs.bench}/mesh.ply
      bottle: None # ${..path_meshes}/bottle/${co3d_refs.bottle}/mesh.ply
      couch: None # ${..path_meshes}/couch/${co3d_refs.couch}/mesh.ply
      cup: None # ${..path_meshes}/cup/${co3d_refs.cup}/mesh.ply
      suitcase: None # ${..path_meshes}/suitcase/${co3d_refs.suitcase}/mesh.ply
      tv: None # ${..path_meshes}/tv/${co3d_refs.tv}/mesh.ply

    fpaths_meshes_tform_obj:
      bicycle: None # ${..path_meshes_tform}/bicycle/${co3d_refs.bicycle}/tform_obj.pt
      truck: None # ${..path_meshes_tform}/toytruck/${co3d_refs.toytruck}/tform_obj.pt
      train: None # ${..path_meshes_tform}/toytrain/${co3d_refs.toytrain}/tform_obj.pt
      teddybear: None # ${..path_meshes_tform}/teddybear/${co3d_refs.teddybear}/tform_obj.pt
      car: None # ${..path_meshes_tform}/car/${co3d_refs.car}/tform_obj.pt
      bus: None # ${..path_meshes_tform}/toybus/${co3d_refs.toybus}/tform_obj.pt
      motorcycle: None # ${..path_meshes_tform}/motorcycle/${co3d_refs.motorcycle}/tform_obj.pt
      keyboard: None # ${..path_meshes_tform}/keyboard/${co3d_refs.keyboard}/tform_obj.pt
      handbag: None # ${..path_meshes_tform}/handbag/${co3d_refs.handbag}/tform_obj.pt
      remote: None # ${..path_meshes_tform}/remote/${co3d_refs.remote}/tform_obj.pt
      airplane: None # ${..path_meshes_tform}/toyplane/${co3d_refs.toyplane}/tform_obj.pt
      toilet: None # ${..path_meshes_tform}/toilet/${co3d_refs.toilet}/tform_obj.pt
      hairdryer: None # ${..path_meshes_tform}/hairdryer/${co3d_refs.hairdryer}/tform_obj.pt
      mouse: None # ${..path_meshes_tform}/mouse/${co3d_refs.mouse}/tform_obj.pt
      toaster: None # ${..path_meshes_tform}/toaster/${co3d_refs.toaster}/tform_obj.pt
      hydrant: None # ${..path_meshes_tform}/hydrant/${co3d_refs.hydrant}/tform_obj.pt
      chair: None # ${..path_meshes_tform}/chair/${co3d_refs.chair}/tform_obj.pt
      laptop: None # ${..path_meshes_tform}/laptop/${co3d_refs.laptop}/tform_obj.pt
      book: None # ${..path_meshes_tform}/book/${co3d_refs.book}/tform_obj.pt
      backpack: None # ${..path_meshes_tform}/backpack/${co3d_refs.backpack}/tform_obj.pt
      cellphone: None # ${..path_meshes_tform}/cellphone/${co3d_refs.cellphone}/tform_obj.pt
      microwave: None # ${..path_meshes_tform}/microwave/${co3d_refs.microwave}/tform_obj.pt
      bench: None # ${..path_meshes_tform}/bench/${co3d_refs.bench}/tform_obj.pt
      bottle: None # ${..path_meshes_tform}/bottle/${co3d_refs.bottle}/tform_obj.pt
      couch: None # ${..path_meshes_tform}/couch/${co3d_refs.couch}/tform_obj.pt
      cup: None # ${..path_meshes_tform}/cup/${co3d_refs.cup}/tform_obj.pt
      suitcase: None # ${..path_meshes_tform}/suitcase/${co3d_refs.suitcase}/tform_obj.pt
      tv: None # ${..path_meshes_tform}/tv/${co3d_refs.tv}/tform_obj.pt

train_datasets:
  labeled:
    modalities: ${modalities}
    categories: ${categories}

val_datasets:
  main:
    modalities: ${modalities}
    categories: ${categories}

test_datasets:
  co3d:
    modalities: ${modalities}
    skip: ${skip_co3d_no_zsp_test}
    subset_fraction: ${test_subset_fraction}
    categories: ${categories}
